name: 'Landing Zone early validation'
description: 'Performs an early validation on the LZ repository to fail as early as possible'
inputs:
  repo-path:  # id of input
    description: 'Location of the repository in your virtual environment'
    required: true
    default: "$GITHUB_WORKSPACE"
outputs:
  validation-result:
    description: 'The result of the validation'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-path }}
